/* DO NOT EDIT THIS FILE - it is machine generated */
#include <com_codekong_ndkdemo_JNITest.h>
/* Header for class com_codekong_ndkdemo_JNITest */

/*
 * Class:     com_codekong_ndkdemo_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codekong_ndkdemo_JNITest_getString
  (JNIEnv * env, jobject jobject){

  return (*env).NewStringUTF("成功调用JNI内容");

  }